SELECT 
    HDR.STARTTIME AS "STARTTIME",
    HDR.OPERATORID AS "OPERATORID",
    HDR.PARTNUMBER AS "PARTNUMBER",
    CASE THM.MISCDESC WHEN 'Process' THEN THM.MISCVALUE END AS "Process",
    CASE NAN.DEVICENAME WHEN 'Nanospec' THEN NAN.DEVICENAME || NAN.DEVICESERIALNUMBER END AS "Nanospec",
    CASE DRY.DEVICENAME WHEN 'DryEtch' THEN DRY.DEVICENAME || DRY.DEVICESERIALNUMBER END AS "DryEtch",
    HDR.SERIALNUMBER AS "SERIALNUMBER",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.Initial1' THEN MSD.VALUE END) AS "Thickness1.Initial1",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.Initial2' THEN MSD.VALUE END) AS "Thickness1.Initial2",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.Initial3' THEN MSD.VALUE END) AS "Thickness1.Initial3",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.Initial4' THEN MSD.VALUE END) AS "Thickness1.Initial4",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.Initial5' THEN MSD.VALUE END) AS "Thickness1.Initial5",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.Initial_Ave' THEN MSD.VALUE END) AS "Thickness1.Initial_Ave",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Rate.Rate1' THEN MSD.VALUE END) AS "Rate.Rate1",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Rate.Rate2' THEN MSD.VALUE END) AS "Rate.Rate2",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Rate.Rate_Ave' THEN MSD.VALUE END) AS "Rate.Rate_Ave",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Coordinate.X1' THEN MSD.VALUE END) AS "X1",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Coordinate.Y1' THEN MSD.VALUE END) AS "Y1"
FROM
    TDSMFG.TESTHEADER HDR
JOIN TDSMFG.TESTHEADERMISC THM ON HDR.TESTHEADERID = THM.TESTHEADERID
JOIN TDSMFG.TESTHEADERSTEP HDS ON HDS.TESTHEADERID = HDR.TESTHEADERID
JOIN TDSMFG.OPERATIONSTEP OPS ON HDS.OPERATIONSTEPID = OPS.OPERATIONSTEPID
JOIN TDSMFG.MEASUREMENTPARAMETER MSP ON HDS.TESTHEADERSTEPID = MSP.TESTHEADERSTEPID
JOIN TDSMFG.MEASUREMENT MSD ON MSP.MEASUREMENTPARAMETERID = MSD.MEASUREMENTPARAMETERID
JOIN TDSMFG.PARAMETER PAR ON MSP.PARAMETERID = PAR.PARAMETERID
LEFT JOIN TDSMFG.TESTEQUIPMENT NAN ON NAN.TESTHEADERID = HDR.TESTHEADERID AND NAN.DEVICENAME = 'Nanospec'
LEFT JOIN TDSMFG.TESTEQUIPMENT DRY ON DRY.TESTHEADERID = HDR.TESTHEADERID AND DRY.DEVICENAME || DRY.DEVICESERIALNUMBER LIKE 'DryEtch#%'
WHERE HDR.OPERATION = 'BJ1_CVD_EtchingRate'
GROUP BY 
    HDR.STARTTIME,
    HDR.OPERATORID,
    HDR.PARTNUMBER,
    HDR.SERIALNUMBER,
    THM.MISCDESC,
    THM.MISCVALUE,
    NAN.DEVICENAME,
    NAN.DEVICESERIALNUMBER,
    DRY.DEVICENAME,
    DRY.DEVICESERIALNUMBER
ORDER BY 
    HDR.STARTTIME;
