SELECT 
    HDR.STARTTIME AS "STARTTIME",
    HDR.OPERATORID AS "OPERATORID",
    HDR.PARTNUMBER AS "PARTNUMBER",
    HDR.SERIALNUMBER AS "SERIALNUMBER",
    TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER AS "EQUIPMENT",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth1.First1' THEN MSD.VALUE END) AS "Depth1.First1",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth1.First2' THEN MSD.VALUE END) AS "Depth1.First2",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth1.First3' THEN MSD.VALUE END) AS "Depth1.First3",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth1.First4' THEN MSD.VALUE END) AS "Depth1.First4",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth1.First5' THEN MSD.VALUE END) AS "Depth1.First5",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth1.First_Ave' THEN MSD.VALUE END) AS "Depth1.First_Ave",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.First1' THEN MSD.VALUE END) AS "Thickness1.First1",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.First2' THEN MSD.VALUE END) AS "Thickness1.First2",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.First3' THEN MSD.VALUE END) AS "Thickness1.First3",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.First4' THEN MSD.VALUE END) AS "Thickness1.First4",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.First5' THEN MSD.VALUE END) AS "Thickness1.First5",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness1.First_Ave' THEN MSD.VALUE END) AS "Thickness1.First_Ave",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'First.Depth' THEN MSD.VALUE END) AS "First.Depth",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'First.Rate' THEN MSD.VALUE END) AS "First.Rate",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Second.Time' THEN MSD.VALUE END) AS "Second.Time",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth2.Second1' THEN MSD.VALUE END) AS "Depth2.Second1",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth2.Second2' THEN MSD.VALUE END) AS "Depth2.Second2",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth2.Second3' THEN MSD.VALUE END) AS "Depth2.Second3",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth2.Second4' THEN MSD.VALUE END) AS "Depth2.Second4",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth2.Second5' THEN MSD.VALUE END) AS "Depth2.Second5",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Depth2.Second_Ave' THEN MSD.VALUE END) AS "Depth2.Second_Ave",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness2.Second1' THEN MSD.VALUE END) AS "Thickness2.Second1",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness2.Second2' THEN MSD.VALUE END) AS "Thickness2.Second2",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness2.Second3' THEN MSD.VALUE END) AS "Thickness2.Second3",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness2.Second4' THEN MSD.VALUE END) AS "Thickness2.Second4",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness2.Second5' THEN MSD.VALUE END) AS "Thickness2.Second5",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Thickness2.Second_Ave' THEN MSD.VALUE END) AS "Thickness2.Second_Ave",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Second.Depth' THEN MSD.VALUE END) AS "Second.Depth",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Second.Rate' THEN MSD.VALUE END) AS "Second.Rate",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Final.Depth' THEN MSD.VALUE END) AS "Final.Depth",
    MAX(CASE WHEN OPS.OPERATIONSTEPNAME || '.' || PAR.PARAMETERNAME = 'Final.Error' THEN MSD.VALUE END) AS "Final.Error"
FROM
    TDSMFG.TESTHEADER           HDR,
    TDSMFG.TESTHEADERSTEP       HDS,
    TDSMFG.OPERATIONSTEP        OPS,
    TDSMFG.MEASUREMENTPARAMETER MSP,
    TDSMFG.MEASUREMENT          MSD,
    TDSMFG.PARAMETER            PAR,
    TDSMFG.TESTEQUIPMENT        TEQ
WHERE 1=1
    AND HDR.TESTHEADERID            = HDS.TESTHEADERID
    AND HDS.OPERATIONSTEPID         = OPS.OPERATIONSTEPID
    AND HDS.TESTHEADERSTEPID        = MSP.TESTHEADERSTEPID
    AND MSP.PARAMETERID             = PAR.PARAMETERID
    AND MSP.MEASUREMENTPARAMETERID  = MSD.MEASUREMENTPARAMETERID
    AND TEQ.TESTHEADERID(+)         = HDR.TESTHEADERID
    AND HDR.OPERATION               = 'BJ1_Crystal_Depth'
GROUP BY
    HDR.STARTTIME,
    HDR.OPERATORID,
    HDR.PARTNUMBER,
    HDR.SERIALNUMBER,
    TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER;
