configs = {
    "rough_polished": {
        "operation": "RoughPolishedThickness",
        "data_sheet_name": "3ｲﾝﾁ用",
        "xy_sheet_name": "ウェハ座標",
        "row_start_date_time": 25,
        "row_serial_number": 24,
        "row_operator": 26,
        "row_polish": 31,
        "col_x" : 2,
        "col_y" : 3,
    },
    "wax_thickness": {
        "operation": "WaxThickness",
        "data_sheet_name": "3ｲﾝﾁ用",
        "xy_sheet_name": "ウェハ座標",
        "row_start_date_time": 25,
        "row_serial_number": 24,
        "row_operator": 26,
        "row_polish": 30,
        "col_x" : 2,
        "col_y" : 3,        
    },
    "mirror_polished": {
        "operation": "MirrorPolishedThickness",
        "data_sheet_name": "3ｲﾝﾁ用",
        "xy_sheet_name": "ウェハ座標",
        "row_start_date_time": 37,
        "row_serial_number": 36,
        "row_operator": 38,
        "row_polish": 46,
        "col_x" : 2,
        "col_y" : 3,        
    },
    "etched_thickness": {
        "operation": "EtchedThickness",
        "data_sheet_name": "3ｲﾝﾁ用",
        "xy_sheet_name": "ウェハ座標",
        "row_start_date_time": 72,
        "row_serial_number": 4,
        "row_operator": 73,
        "row_polish": 63,
        "col_x" : 2,
        "col_y" : 3,        
    },
    "initial_wafer_thickness": {
        "operation": "InitialWaferThickness",
        "data_sheet_name": "3ｲﾝﾁ用",
        "xy_sheet_name": "ウェハ座標",
        "row_start_date_time": 5,
        "row_serial_number": 4,
        "row_operator": 6,
        "row_polish": 18,
        "col_x" : 2,
        "col_y" : 3,        
    },
}
