SELECT * FROM (
    SELECT
      HDR.STARTTIME,
      HDR.OPERATORID,
      HDR.PARTNUMBER,
      HDR.SERIALNUMBER,
      TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER AS "EQUIPMENT",
      MSD.OPERATIONSTEPNAME || '.' || MSD.PARAMETERNAME AS STEP_AND_PARAMETER,
      MSD.VALUE
    FROM TDSMFG.TESTHEADER_V HDR 
	    INNER JOIN TDSMFG.MEASUREMENT_V MSD ON HDR.TESTHEADERID = MSD.TESTHEADERID
        LEFT JOIN TDSMFG.TESTEQUIPMENT TEQ ON TEQ.TESTHEADERID = HDR.TESTHEADERID  
    where HDR.STARTTIME BETWEEN TRUNC(SYSDATE) - CHART_PERIOD_DAYS AND TRUNC(SYSDATE)
      AND HDR.OPERATION = 'Chip_Thickness_Facet_Coating'
)
PIVOT(
    MAX(VALUE) FOR STEP_AND_PARAMETER IN (
		'THK_DEP.BL_THK' as "THK_DEP.BL_THK",
		'THK_DEP.BR_THK' as "THK_DEP.BR_THK",
		'THK_DEP.Banchi_THK_AVG' as "THK_DEP.Banchi_THK_AVG",
		'THK_DEP.CE_THK' as "THK_DEP.CE_THK",
		'THK_DEP.TL_THK' as "THK_DEP.TL_THK",
		'THK_DEP.TR_THK' as "THK_DEP.TR_THK",  
		'SORTED_DATA.SORTNUMBER' as "SORTED_DATA.SORTNUMBER",      
		'SORTED_DATA.STARTTIME_SORTED' as "SORTED_DATA.STARTTIME_SORTED"
    )
)Int_Data
where Int_Data.SERIALNUMBER NOT IN (CTQ_IGNORED_LIST)    
and SUBSTR(Int_Data.PARTNUMBER,1,6)IN (FOCUSED_LIST)		
ORDER BY
    "SORTED_DATA.STARTTIME_SORTED",
    STARTTIME