SELECT
    Format1_Int_Data.STARTTIME AS Format1_STARTTIME,
    Format1_Int_Data.BATCHNUMBER,
    Format1_String_Data."SIX_BATCHNUMBER",
    Format1_Int_Data.OPERATORID AS Format1_Operator,
    Format1_Int_Data.SERIALNUMBER,
    Format1_String_Data."NINE_SERIALNUMBER",
    Format1_Int_Data.PARTNUMBER,
    Format1_Int_Data."SORTED_DATA_STARTTIME_SORTED",
    Format1_Int_Data."SORTED_DATA_SORTNUMBER",
    Format1_MISC_Data."RecipeName_Macro",
    Format1_MISC_Data."RecipeName_Program",
    Format1_MISC_Data."RecipeName_Folder",
    Format1_Int_Data."SEM",
    Format1_Int_Data."PLmapper" AS "Format1_PLmapper",
    Format1_Int_Data."XRD",
    Format1_Int_Data."MOCVD",
    Format1_Int_Data."X",
    Format1_Int_Data."Y",
    Format1_Int_Data."TargetWavelength",
    Format1_Int_Data."Thickness_Cap",
    Format1_Int_Data."Thickness_Core",
    Format1_Int_Data."Thickness_Total",
    Format1_Int_Data."Xray_Thickness",
    Format1_Int_Data."Xray_Strain",
    Format1_String_Data."InPBoardLot_No",
    Format1_Int_Data."InPBoardLot_CC",
    Format1_Int_Data."InPBoardLot_EPD",
    Format1_Int_Data."Wavelength_EA",
    Format1_Int_Data."Wavelength_Intensity",
    Format1_Int_Data."Wavelength_FWHM",
    Format1_Int_Data."EpiTT_EA",
    Format1_Int_Data."GFR_Setting",
    Format1_Int_Data."GFR-flow",
    Format1_Int_Data."Dulation_Step6",
    Format1_Int_Data."Dulation_Step8",
    Format1_Int_Data."Dulation_Step10",
    Format1_Int_Data."Dulation_Step12-1",
    Format1_Int_Data."Dulation_Step12-2",
    Format1_Int_Data."Dulation_Step12-3",
    Format1_Int_Data."Dulation_Step14",
    Format1_Int_Data."Dulation_Step16",
    Format1_Int_Data."Dulation_Step18",
    Format1_Int_Data."Dulation_Step20",
    Format1_Int_Data."Dulation_Step21",
    Format1_Int_Data."TMGa_1_Step12-2",
    Format1_Int_Data."TMGa_3_Step8",
    Format1_Int_Data."TMGa_3_Step10",
    Format1_Int_Data."TMGa_3_Step12-1",
    Format1_Int_Data."TMGa_3_Step12-3",
    Format1_Int_Data."TMGa_3_Step14",
    Format1_Int_Data."TMGa_3_Step16",
    Format1_Int_Data."TMGa_3_Step18",
    Format1_Int_Data."TMIn_1_Step6",
    Format1_Int_Data."TMIn_1_Step8",
    Format1_Int_Data."TMIn_1_Step10",
    Format1_Int_Data."TMIn_1_Step12-1",
    Format1_Int_Data."TMIn_1_Step12-2",
    Format1_Int_Data."TMIn_1_Step12-3",
    Format1_Int_Data."TMIn_1_Step14",
    Format1_Int_Data."TMIn_1_Step16",
    Format1_Int_Data."TMIn_1_Step18",
    Format1_Int_Data."TMIn_1_Step20",
    Format1_Int_Data."TMIn_1_Step21",
    Format1_Int_Data."TMIn_2_Step6",
    Format1_Int_Data."TMIn_2_Step8",
    Format1_Int_Data."TMIn_2_Step10",
    Format1_Int_Data."TMIn_2_Step12-1",
    Format1_Int_Data."TMIn_2_Step12-2",
    Format1_Int_Data."TMIn_2_Step12-3",
    Format1_Int_Data."TMIn_2_Step14",
    Format1_Int_Data."TMIn_2_Step16",
    Format1_Int_Data."TMIn_2_Step18",
    Format1_Int_Data."TMIn_2_Step20",
    Format1_Int_Data."TMIn_2_Step21",
    Format1_Int_Data."DMZn_1_Step21",
    Format1_Int_Data."Si2H6_100ppm_Step6",
    Format1_Int_Data."Si2H6_100ppm_Step8",
    Format1_Int_Data."Si2H6_100ppm_Step10",
    Format1_Int_Data."PH3_1_100percent_Step6",
    Format1_Int_Data."PH3_1_100percent_Step8",
    Format1_Int_Data."PH3_1_100percent_Step10",
    Format1_Int_Data."PH3_1_100percent_Step12-1",
    Format1_Int_Data."PH3_1_100percent_Step12-2",
    Format1_Int_Data."PH3_1_100percent_Step12-3",
    Format1_Int_Data."PH3_1_100percent_Step14",
    Format1_Int_Data."PH3_1_100percent_Step16",
    Format1_Int_Data."PH3_1_100percent_Step18",
    Format1_Int_Data."PH3_1_100percent_Step20",
    Format1_Int_Data."PH3_1_100percent_Step21",
    Format1_Int_Data."PH3_2_100percent_Step6",
    Format1_Int_Data."PH3_2_100percent_Step8",
    Format1_Int_Data."PH3_2_100percent_Step10",
    Format1_Int_Data."PH3_2_100percent_Step12-1",
    Format1_Int_Data."PH3_2_100percent_Step12-2",
    Format1_Int_Data."PH3_2_100percent_Step12-3",
    Format1_Int_Data."PH3_2_100percent_Step14",
    Format1_Int_Data."PH3_2_100percent_Step16",
    Format1_Int_Data."PH3_2_100percent_Step18",
    Format1_Int_Data."PH3_2_100percent_Step20",
    Format1_Int_Data."PH3_2_100percent_Step21",
    Format1_Int_Data."AsH3_2_100percent_Step12-2",
    Format1_Int_Data."AsH3_3_100percent_Step8",
    Format1_Int_Data."AsH3_3_100percent_Step10",
    Format1_Int_Data."AsH3_3_100percent_Step12-1",
    Format1_Int_Data."AsH3_3_100percent_Step12-3",
    Format1_Int_Data."AsH3_3_100percent_Step14",
    Format1_Int_Data."AsH3_3_100percent_Step16",
    Format1_Int_Data."AsH3_3_100percent_Step18",
    Format1_Int_Data."GrowthTemperature_Step6",
    Format1_Int_Data."GrowthTemperature_Step8",
    Format1_Int_Data."GrowthTemperature_Step10",
    Format1_Int_Data."GrowthTemperature_Step12-1",
    Format1_Int_Data."GrowthTemperature_Step12-2",
    Format1_Int_Data."GrowthTemperature_Step12-3",
    Format1_Int_Data."GrowthTemperature_Step14",
    Format1_Int_Data."GrowthTemperature_Step16",
    Format1_Int_Data."GrowthTemperature_Step18",
    Format1_Int_Data."GrowthTemperature_Step20",
    Format1_Int_Data."GrowthTemperature_Step21",
    Format1_String_Data."LayerNo_Step6",
    Format1_String_Data."LayerNo_Step8",
    Format1_String_Data."LayerNo_Step10",
    Format1_String_Data."LayerNo_Step12-1",
    Format1_String_Data."LayerNo_Step12-2",
    Format1_String_Data."LayerNo_Step12-3",
    Format1_String_Data."LayerNo_Step14",
    Format1_String_Data."LayerNo_Step16",
    Format1_String_Data."LayerNo_Step18",
    Format1_String_Data."LayerNo_Step20",
    Format1_String_Data."LayerNo_Step21",
    Format1_String_Data."Comment_Step6",
    Format1_String_Data."Comment_Step8",
    Format1_String_Data."Comment_Step10",
    Format1_String_Data."Comment_Step12-1",
    Format1_String_Data."Comment_Step12-2",
    Format1_String_Data."Comment_Step12-3",
    Format1_String_Data."Comment_Step14",
    Format1_String_Data."Comment_Step16",
    Format1_String_Data."Comment_Step18",
    Format1_String_Data."Comment_Step20",
    Format1_String_Data."Comment_Step21",
    Format1_Int_Data."Thickness_Step_Step6",
    Format1_Int_Data."Thickness_Step_Step8",
    Format1_Int_Data."Thickness_Step_Step10",
    Format1_Int_Data."Thickness_Step_Step12-1",
    Format1_Int_Data."Thickness_Step_Step12-2",
    Format1_Int_Data."Thickness_Step_Step12-3",
    Format1_Int_Data."Thickness_Step_Step14",
    Format1_Int_Data."Thickness_Step_Step16",
    Format1_Int_Data."Thickness_Step_Step18",
    Format1_Int_Data."Thickness_Step_Step20",
    Format1_Int_Data."Thickness_Step_Step21",
    Format1_Int_Data."CarrierConcentration_Step6",
    Format1_Int_Data."CarrierConcentration_Step8",
    Format1_Int_Data."CarrierConcentration_Step10",
    Format1_Int_Data."CarrierConcentration_Step21",
    Format1_Int_Data."MO-level_TMGa_1",
    Format1_Int_Data."MO-level_TMGa_2",
    Format1_Int_Data."MO-level_TMGa_3",
    Format1_Int_Data."MO-level_TMIn_1",
    Format1_Int_Data."MO-level_TMIn_2",
    Format1_Int_Data."MO-level_TMIn_3",
    Format1_Int_Data."MO-level_DEZn_1",
    Format1_Int_Data."MO-level_DMZn_1",
    Format1_Int_Data."MO-level_TMAl_1",
    Format1_Int_Data."MO-level_TMAl_2",
    Format1_Int_Data."MO-level_AMAl_3",
    Format1_Int_Data."As-Ratio_Step8",
    Format1_Int_Data."As-Ratio_Step10",
    Format1_Int_Data."As-Ratio_Step12-1",
    Format1_Int_Data."As-Ratio_Step12-2",
    Format1_Int_Data."As-Ratio_Step12-3",
    Format1_Int_Data."As-Ratio_Step14",
    Format1_Int_Data."As-Ratio_Step16",
    Format1_Int_Data."As-Ratio_Step18",
    Format1_Int_Data."Ga-Ratio_Step8",
    Format1_Int_Data."Ga-Ratio_Step10",
    Format1_Int_Data."Ga-Ratio_Step12-1",
    Format1_Int_Data."Ga-Ratio_Step12-2",
    Format1_Int_Data."Ga-Ratio_Step12-3",
    Format1_Int_Data."Ga-Ratio_Step14",
    Format1_Int_Data."Ga-Ratio_Step16",
    Format1_Int_Data."Ga-Ratio_Step18",
    Format2.STARTTIME AS Format2_STARTTIME,
    Format2.OPERATORID AS Format2_OPERATOR,
    Format2.SERIALNUMBER AS Format2_SERIALNUMBER,
    Format2."PLmapper" AS Format2_PLmapper,
    Format2."Mapper_3sigma_Mapper_PL_Lambda",
    Format2."Mapper_3sigma_Mapper_PL_Intensity",
    Format2."Mapper_3sigma_Mapper_PL_FWHM",
    Format2."Mapper_Average_Mapper_PL_Lambda",
    Format2."Mapper_Average_Mapper_PL_Intensity",
    Format2."Mapper_Average_Mapper_PL_FWHM",
    Format2."Mapper_Average_Mapper_PL_StrengthRatio",
    Format2."Mapper_TargetWavelength",
    Format2."Mapper_Wavelength(1.3um)",
    Format2."Mapper_CheckingAdjustValue",
    Format2."Center_X",
    Format2."Center_Y",
    Format2."Center_Lambda",
    Format2."Center_Intensity",
    Format2."Center_FWHM",
    Format2."Center_Tails",
    Format2."Center_DeltaLambda",
    Format2."A_X",
    Format2."A_Y",
    Format2."A_Lambda",
    Format2."A_Intensity",
    Format2."A_FWHM",
    Format2."A_Tails",
    Format2."A_DeltaLambda",
    Format2."B_X",
    Format2."B_Y",
    Format2."B_Lambda",
    Format2."B_Intensity",
    Format2."B_FWHM",
    Format2."B_Tails",
    Format2."B_DeltaLambda",
    Format2."C_X",
    Format2."C_Y",
    Format2."C_Lambda",
    Format2."C_Intensity",
    Format2."C_FWHM",
    Format2."C_Tails",
    Format2."C_DeltaLambda",
    Format2."D_X",
    Format2."D_Y",
    Format2."D_Lambda",
    Format2."D_Intensity",
    Format2."D_FWHM",
    Format2."D_Tails",
    Format2."D_DeltaLambda",
    Format2."AB_X",
    Format2."AB_Y",
    Format2."AB_Lambda",
    Format2."AB_Intensity",
    Format2."AB_FWHM",
    Format2."AB_Tails",
    Format2."AB_DeltaLambda",
    Format2."AC_X",
    Format2."AC_Y",
    Format2."AC_Lambda",
    Format2."AC_Intensity",
    Format2."AC_FWHM",
    Format2."AC_Tails",
    Format2."AC_DeltaLambda",
    Format2."BC_X",
    Format2."BC_Y",
    Format2."BC_Lambda",
    Format2."BC_Intensity",
    Format2."BC_FWHM",
    Format2."BC_Tails",
    Format2."BC_DeltaLambda",
    Format2."CD_X",
    Format2."CD_Y",
    Format2."CD_Lambda",
    Format2."CD_Intensity",
    Format2."CD_FWHM",
    Format2."CD_Tails",
    Format2."CD_DeltaLambda",
    Format2."AA_X",
    Format2."AA_Y",
    Format2."AA_Lambda",
    Format2."AA_Intensity",
    Format2."AA_FWHM",
    Format2."AA_Tails",
    Format2."AA_DeltaLambda",
    Format2."BB_X",
    Format2."BB_Y",
    Format2."BB_Lambda",
    Format2."BB_Intensity",
    Format2."BB_FWHM",
    Format2."BB_Tails",
    Format2."BB_DeltaLambda",
    Format2."CC_X",
    Format2."CC_Y",
    Format2."CC_Lambda",
    Format2."CC_Intensity",
    Format2."CC_FWHM",
    Format2."CC_Tails",
    Format2."CC_DeltaLambda",
    Format2."DD_X",
    Format2."DD_Y",
    Format2."DD_Lambda",
    Format2."DD_Intensity",
    Format2."DD_FWHM",
    Format2."DD_Tails",
    Format2."DD_DeltaLambda",
    Format2."Addr32GravityLambda",
    Format2."AreaStandards_1",
    Format2."AreaStandards_2",
    Format2."Mapper_PL"
FROM(
    SELECT
        HDR.TESTHEADERID,
        HDR.STARTTIME,
        HDR.PARTNUMBER,
        HDR.SERIALNUMBER,
        HDR.OPERATORID,
        HDR.BATCHNUMBER,
        MAX(CASE TEQ.DEVICENAME WHEN 'SEM' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "SEM",
        MAX(CASE TEQ.DEVICENAME WHEN 'PLmapper' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "PLmapper",
        MAX(CASE TEQ.DEVICENAME WHEN 'XRD' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "XRD",
        MAX(CASE TEQ.DEVICENAME WHEN 'MOCVD' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "MOCVD",
        OPS.OPERATIONSTEPNAME || '_' || PARAMETERNAME AS TESTSTEPS,
        MSD.VALUE
    FROM
        TDSMFG.TESTHEADER           HDR,
        TDSMFG.TESTHEADERMISC       THM,
        TDSMFG.TESTHEADERSTEP       HDS,
        TDSMFG.OPERATIONSTEP        OPS,
        TDSMFG.MEASUREMENTPARAMETER MSP,
        TDSMFG.MEASUREMENT          MSD,
        TDSMFG.PARAMETER            PAR,
        TDSMFG.TESTEQUIPMENT        TEQ
    WHERE 1=1
        AND HDR.TESTHEADERID            = HDS.TESTHEADERID
        AND HDR.TESTHEADERID            = THM.TESTHEADERID
        AND HDS.TESTHEADERSTEPID        = MSP.TESTHEADERSTEPID
        AND HDS.OPERATIONSTEPID         = OPS.OPERATIONSTEPID
        AND MSP.MEASUREMENTPARAMETERID  = MSD.MEASUREMENTPARAMETERID
        AND MSP.PARAMETERID             = PAR.PARAMETERID
        AND HDR.TESTHEADERID            = TEQ.TESTHEADERID(+)
        AND HDR.OPERATION               = 'EA-EML_F7_Format1'
    GROUP BY
        HDR.TESTHEADERID,
        STARTTIME,
        PARTNUMBER,
        SERIALNUMBER,
        OPERATORID,
        BATCHNUMBER,
        OPERATIONSTEPNAME,
        PARAMETERNAME,
        VALUE
    )
    PIVOT(
        MAX(VALUE) FOR TESTSTEPS IN(
            'Coordinate_X' AS "X",
            'Coordinate_Y' AS "Y",
            'TargetWavelength_TargetWavelength' AS "TargetWavelength",
            'Thickness_Thickness_Cap' AS "Thickness_Cap",
            'Thickness_Thickness_Core' AS "Thickness_Core",
            'Thickness_Thickness_Total' AS "Thickness_Total",
            'XRayDiffraction_Xray_Thickness' AS "Xray_Thickness",
            'XRayDiffraction_Xray_Strain' AS "Xray_Strain",
            'InPBoardLot_InPBoardLot_CC' AS "InPBoardLot_CC",
            'InPBoardLot_InPBoardLot_EPD' AS "InPBoardLot_EPD",
            'Wavelength_Wavelength_EA' AS "Wavelength_EA",
            'Wavelength_Wavelength_Intensity' AS "Wavelength_Intensity",
            'Wavelength_Wavelength_FWHM' AS "Wavelength_FWHM",
            'EpiTT_EpiTT_EA' AS "EpiTT_EA",
            'GFR_GFR_Setting' AS "GFR_Setting",
            'GFR-flow_GFR-flow' AS "GFR-flow",
            'Dulation_Step6' AS "Dulation_Step6",
            'Dulation_Step8' AS "Dulation_Step8",
            'Dulation_Step10' AS "Dulation_Step10",
            'Dulation_Step12-1' AS "Dulation_Step12-1",
            'Dulation_Step12-2' AS "Dulation_Step12-2",
            'Dulation_Step12-3' AS "Dulation_Step12-3",
            'Dulation_Step14' AS "Dulation_Step14",
            'Dulation_Step16' AS "Dulation_Step16",
            'Dulation_Step18' AS "Dulation_Step18",
            'Dulation_Step20' AS "Dulation_Step20",
            'Dulation_Step21' AS "Dulation_Step21",
            'TMGa_1_Step12-2' AS "TMGa_1_Step12-2",
            'TMGa_3_Step8' AS "TMGa_3_Step8",
            'TMGa_3_Step10' AS "TMGa_3_Step10",
            'TMGa_3_Step12-1' AS "TMGa_3_Step12-1",
            'TMGa_3_Step12-3' AS "TMGa_3_Step12-3",
            'TMGa_3_Step14' AS "TMGa_3_Step14",
            'TMGa_3_Step16' AS "TMGa_3_Step16",
            'TMGa_3_Step18' AS "TMGa_3_Step18",
            'TMIn_1_Step6' AS "TMIn_1_Step6",
            'TMIn_1_Step8' AS "TMIn_1_Step8",
            'TMIn_1_Step10' AS "TMIn_1_Step10",
            'TMIn_1_Step12-1' AS "TMIn_1_Step12-1",
            'TMIn_1_Step12-2' AS "TMIn_1_Step12-2",
            'TMIn_1_Step12-3' AS "TMIn_1_Step12-3",
            'TMIn_1_Step14' AS "TMIn_1_Step14",
            'TMIn_1_Step16' AS "TMIn_1_Step16",
            'TMIn_1_Step18' AS "TMIn_1_Step18",
            'TMIn_1_Step20' AS "TMIn_1_Step20",
            'TMIn_1_Step21' AS "TMIn_1_Step21",
            'TMIn_2_Step6' AS "TMIn_2_Step6",
            'TMIn_2_Step8' AS "TMIn_2_Step8",
            'TMIn_2_Step10' AS "TMIn_2_Step10",
            'TMIn_2_Step12-1' AS "TMIn_2_Step12-1",
            'TMIn_2_Step12-2' AS "TMIn_2_Step12-2",
            'TMIn_2_Step12-3' AS "TMIn_2_Step12-3",
            'TMIn_2_Step14' AS "TMIn_2_Step14",
            'TMIn_2_Step16' AS "TMIn_2_Step16",
            'TMIn_2_Step18' AS "TMIn_2_Step18",
            'TMIn_2_Step20' AS "TMIn_2_Step20",
            'TMIn_2_Step21' AS "TMIn_2_Step21",
            'DMZn_1_Step21' AS "DMZn_1_Step21",
            'Si2H6_100ppm_Step6' AS "Si2H6_100ppm_Step6",
            'Si2H6_100ppm_Step8' AS "Si2H6_100ppm_Step8",
            'Si2H6_100ppm_Step10' AS "Si2H6_100ppm_Step10",
            'PH3_1_100percent_Step6' AS "PH3_1_100percent_Step6",
            'PH3_1_100percent_Step8' AS "PH3_1_100percent_Step8",
            'PH3_1_100percent_Step10' AS "PH3_1_100percent_Step10",
            'PH3_1_100percent_Step12-1' AS "PH3_1_100percent_Step12-1",
            'PH3_1_100percent_Step12-2' AS "PH3_1_100percent_Step12-2",
            'PH3_1_100percent_Step12-3' AS "PH3_1_100percent_Step12-3",
            'PH3_1_100percent_Step14' AS "PH3_1_100percent_Step14",
            'PH3_1_100percent_Step16' AS "PH3_1_100percent_Step16",
            'PH3_1_100percent_Step18' AS "PH3_1_100percent_Step18",
            'PH3_1_100percent_Step20' AS "PH3_1_100percent_Step20",
            'PH3_1_100percent_Step21' AS "PH3_1_100percent_Step21",
            'PH3_2_100percent_Step6' AS "PH3_2_100percent_Step6",
            'PH3_2_100percent_Step8' AS "PH3_2_100percent_Step8",
            'PH3_2_100percent_Step10' AS "PH3_2_100percent_Step10",
            'PH3_2_100percent_Step12-1' AS "PH3_2_100percent_Step12-1",
            'PH3_2_100percent_Step12-2' AS "PH3_2_100percent_Step12-2",
            'PH3_2_100percent_Step12-3' AS "PH3_2_100percent_Step12-3",
            'PH3_2_100percent_Step14' AS "PH3_2_100percent_Step14",
            'PH3_2_100percent_Step16' AS "PH3_2_100percent_Step16",
            'PH3_2_100percent_Step18' AS "PH3_2_100percent_Step18",
            'PH3_2_100percent_Step20' AS "PH3_2_100percent_Step20",
            'PH3_2_100percent_Step21' AS "PH3_2_100percent_Step21",
            'AsH3_2_100percent_Step12-2' AS "AsH3_2_100percent_Step12-2",
            'AsH3_3_100percent_Step8' AS "AsH3_3_100percent_Step8",
            'AsH3_3_100percent_Step10' AS "AsH3_3_100percent_Step10",
            'AsH3_3_100percent_Step12-1' AS "AsH3_3_100percent_Step12-1",
            'AsH3_3_100percent_Step12-2' AS "AsH3_3_100percent_Step12-2",
            'AsH3_3_100percent_Step12-3' AS "AsH3_3_100percent_Step12-3",
            'AsH3_3_100percent_Step14' AS "AsH3_3_100percent_Step14",
            'AsH3_3_100percent_Step16' AS "AsH3_3_100percent_Step16",
            'AsH3_3_100percent_Step18' AS "AsH3_3_100percent_Step18",
            'GrowthTemperature_Step6' AS "GrowthTemperature_Step6",
            'GrowthTemperature_Step8' AS "GrowthTemperature_Step8",
            'GrowthTemperature_Step10' AS "GrowthTemperature_Step10",
            'GrowthTemperature_Step12-1' AS "GrowthTemperature_Step12-1",
            'GrowthTemperature_Step12-2' AS "GrowthTemperature_Step12-2",
            'GrowthTemperature_Step12-3' AS "GrowthTemperature_Step12-3",
            'GrowthTemperature_Step14' AS "GrowthTemperature_Step14",
            'GrowthTemperature_Step16' AS "GrowthTemperature_Step16",
            'GrowthTemperature_Step18' AS "GrowthTemperature_Step18",
            'GrowthTemperature_Step20' AS "GrowthTemperature_Step20",
            'GrowthTemperature_Step21' AS "GrowthTemperature_Step21",
            'Thickness_Step_Step6' AS "Thickness_Step_Step6",
            'Thickness_Step_Step8' AS "Thickness_Step_Step8",
            'Thickness_Step_Step10' AS "Thickness_Step_Step10",
            'Thickness_Step_Step12-1' AS "Thickness_Step_Step12-1",
            'Thickness_Step_Step12-2' AS "Thickness_Step_Step12-2",
            'Thickness_Step_Step12-3' AS "Thickness_Step_Step12-3",
            'Thickness_Step_Step14' AS "Thickness_Step_Step14",
            'Thickness_Step_Step16' AS "Thickness_Step_Step16",
            'Thickness_Step_Step18' AS "Thickness_Step_Step18",
            'Thickness_Step_Step20' AS "Thickness_Step_Step20",
            'Thickness_Step_Step21' AS "Thickness_Step_Step21",
            'CarrierConcentration_Step6' AS "CarrierConcentration_Step6",
            'CarrierConcentration_Step8' AS "CarrierConcentration_Step8",
            'CarrierConcentration_Step10' AS "CarrierConcentration_Step10",
            'CarrierConcentration_Step21' AS "CarrierConcentration_Step21",
            'MO-level_TMGa_1' AS "MO-level_TMGa_1",
            'MO-level_TMGa_2' AS "MO-level_TMGa_2",
            'MO-level_TMGa_3' AS "MO-level_TMGa_3",
            'MO-level_TMIn_1' AS "MO-level_TMIn_1",
            'MO-level_TMIn_2' AS "MO-level_TMIn_2",
            'MO-level_TMIn_3' AS "MO-level_TMIn_3",
            'MO-level_DEZn_1' AS "MO-level_DEZn_1",
            'MO-level_DMZn_1' AS "MO-level_DMZn_1",
            'MO-level_TMAl_1' AS "MO-level_TMAl_1",
            'MO-level_TMAl_2' AS "MO-level_TMAl_2",
            'MO-level_AMAl_3' AS "MO-level_AMAl_3",
            'As-Ratio_Step8' AS "As-Ratio_Step8",
            'As-Ratio_Step10' AS "As-Ratio_Step10",
            'As-Ratio_Step12-1' AS "As-Ratio_Step12-1",
            'As-Ratio_Step12-2' AS "As-Ratio_Step12-2",
            'As-Ratio_Step12-3' AS "As-Ratio_Step12-3",
            'As-Ratio_Step14' AS "As-Ratio_Step14",
            'As-Ratio_Step16' AS "As-Ratio_Step16",
            'As-Ratio_Step18' AS "As-Ratio_Step18",
            'Ga-Ratio_Step8' As "Ga-Ratio_Step8",
            'Ga-Ratio_Step10' As "Ga-Ratio_Step10",
            'Ga-Ratio_Step12-1' As "Ga-Ratio_Step12-1",
            'Ga-Ratio_Step12-2' As "Ga-Ratio_Step12-2",
            'Ga-Ratio_Step12-3' As "Ga-Ratio_Step12-3",
            'Ga-Ratio_Step14' As "Ga-Ratio_Step14",
            'Ga-Ratio_Step16' As "Ga-Ratio_Step16",
            'Ga-Ratio_Step18' As "Ga-Ratio_Step18",
            'SORTED_DATA_STARTTIME_SORTED' AS "SORTED_DATA_STARTTIME_SORTED",
            'SORTED_DATA_SORTNUMBER' AS "SORTED_DATA_SORTNUMBER"
        )
    )Format1_Int_Data
    LEFT JOIN
    (
        SELECT
            HDR.SERIALNUMBER,
            THM.MISCVALUE,
            THM.MISCDESC
        FROM
            TDSMFG.TESTHEADER           HDR,
            TDSMFG.TESTHEADERMISC       THM
        WHERE
            HDR.TESTHEADERID            = THM.TESTHEADERID
            AND HDR.OPERATION               = 'EA-EML_F7_Format1'
    )
    PIVOT(
        MAX(MISCVALUE) FOR MISCDESC IN(
            'RecipeName-Macro' AS "RecipeName_Macro",
            'RecipeName-Program' AS "RecipeName_Program",
            'RecipeName-Folder' AS "RecipeName_Folder"
        )
    )Format1_MISC_Data
    ON Format1_Int_Data.SERIALNUMBER = Format1_MISC_Data.SERIALNUMBER
    LEFT JOIN
    (
        SELECT
            HDR.TESTHEADERID,
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'SORTED_DATA_LotNumber_5' THEN VALUESTRING END) AS "FIVE_SERIALNUMBER",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'SORTED_DATA_LotNumber_9' THEN VALUESTRING END) AS "NINE_SERIALNUMBER",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'SORTED_DATA_BATCHNUMBER_SORTED' THEN VALUESTRING END) AS "SIX_BATCHNUMBER",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'InPBoardLot_InPBoardLot_No' THEN VALUESTRING END) AS "InPBoardLot_No",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step6' THEN VALUESTRING END) AS "LayerNo_Step6",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step8' THEN VALUESTRING END) AS "LayerNo_Step8",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step10' THEN VALUESTRING END) AS "LayerNo_Step10",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step12-1' THEN VALUESTRING END) AS "LayerNo_Step12-1",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step12-2' THEN VALUESTRING END) AS "LayerNo_Step12-2",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step12-3' THEN VALUESTRING END) AS "LayerNo_Step12-3",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step14' THEN VALUESTRING END) AS "LayerNo_Step14",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step16' THEN VALUESTRING END) AS "LayerNo_Step16",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step18' THEN VALUESTRING END) AS "LayerNo_Step18",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step20' THEN VALUESTRING END) AS "LayerNo_Step20",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step21' THEN VALUESTRING END) AS "LayerNo_Step21",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step6' THEN VALUESTRING END) AS "Comment_Step6",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step8' THEN VALUESTRING END) AS "Comment_Step8",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step10' THEN VALUESTRING END) AS "Comment_Step10",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step12-1' THEN VALUESTRING END) AS "Comment_Step12-1",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step12-2' THEN VALUESTRING END) AS "Comment_Step12-2",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step12-3' THEN VALUESTRING END) AS "Comment_Step12-3",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step14' THEN VALUESTRING END) AS "Comment_Step14",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step16' THEN VALUESTRING END) AS "Comment_Step16",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step18' THEN VALUESTRING END) AS "Comment_Step18",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step20' THEN VALUESTRING END) AS "Comment_Step20",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step21' THEN VALUESTRING END) AS "Comment_Step21"
        FROM
            TDSMFG.TESTHEADER           HDR,
            TDSMFG.TESTHEADERSTEP       HDS,
            TDSMFG.OPERATIONSTEP        OPS,
            TDSMFG.PARAMETER            PAR,
            TDSMFG.STRINGPARAMETER      STP,
            TDSMFG.STRINGMEASUREMENT    SMM
        WHERE 1=1
            AND HDR.TESTHEADERID            = HDS.TESTHEADERID
            AND HDS.OPERATIONSTEPID         = OPS.OPERATIONSTEPID
            AND HDS.TESTHEADERSTEPID        = STP.TESTHEADERSTEPID
            AND STP.STRINGPARAMETERID       = SMM.STRINGPARAMETERID
            AND PAR.OPERATIONSTEPID         = OPS.OPERATIONSTEPID
            AND PAR.PARAMETERID             = STP.PARAMETERID
            AND HDR.OPERATION               = 'EA-EML_F7_Format1'
        GROUP BY
            HDR.TESTHEADERID
    )Format1_String_Data
    ON Format1_Int_Data.TESTHEADERID = Format1_String_Data.TESTHEADERID
     FULL JOIN
    (
        SELECT
            HDR.TESTHEADERID,
            HDR.STARTTIME,
            HDR.PARTNUMBER,
            HDR.SERIALNUMBER,
            HDR.OPERATORID,
            HDR.BATCHNUMBER,
            MAX(CASE TEQ.DEVICENAME WHEN 'PLmapper' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "PLmapper",
            MAX(CASE TEQ.DEVICENAME WHEN 'MOCVD' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "MOCVD",
            OPS.OPERATIONSTEPNAME || '_' || PARAMETERNAME AS TESTSTEPS,
            MSD.VALUE
        FROM
            TDSMFG.TESTHEADER           HDR,
            TDSMFG.TESTHEADERSTEP       HDS,
            TDSMFG.OPERATIONSTEP        OPS,
            TDSMFG.MEASUREMENTPARAMETER MSP,
            TDSMFG.MEASUREMENT          MSD,
            TDSMFG.PARAMETER            PAR,
            TDSMFG.TESTEQUIPMENT        TEQ
        WHERE 1=1
            AND HDR.TESTHEADERID            = HDS.TESTHEADERID
            AND HDS.OPERATIONSTEPID         = OPS.OPERATIONSTEPID
            AND HDS.TESTHEADERSTEPID        = MSP.TESTHEADERSTEPID
            AND MSP.MEASUREMENTPARAMETERID  = MSD.MEASUREMENTPARAMETERID
            AND MSP.PARAMETERID             = PAR.PARAMETERID
            AND TEQ.TESTHEADERID(+)         = HDR.TESTHEADERID
            AND HDR.OPERATION               = 'EA-EML_F7_Format2'
        GROUP BY
            HDR.TESTHEADERID,
            STARTTIME,
            PARTNUMBER,
            SERIALNUMBER,
            OPERATORID,
            BATCHNUMBER,
            OPERATIONSTEPNAME,
            PARAMETERNAME,
            VALUE
        )
        PIVOT(
            MAX(VALUE) FOR TESTSTEPS IN(
                'Coordinate_X' AS "X",
                'Coordinate_Y' AS "Y",
                'Mapper_3sigma_Mapper_PL_Lambda' AS "Mapper_3sigma_Mapper_PL_Lambda",
                'Mapper_3sigma_Mapper_PL_Intensity' AS "Mapper_3sigma_Mapper_PL_Intensity",
                'Mapper_3sigma_Mapper_PL_FWHM' AS "Mapper_3sigma_Mapper_PL_FWHM",
                'Mapper_Average_Mapper_PL_Lambda' AS "Mapper_Average_Mapper_PL_Lambda",
                'Mapper_Average_Mapper_PL_Intensity' AS "Mapper_Average_Mapper_PL_Intensity",
                'Mapper_Average_Mapper_PL_FWHM' AS "Mapper_Average_Mapper_PL_FWHM",
                'Mapper_Average_Mapper_PL_StrengthRatio' AS "Mapper_Average_Mapper_PL_StrengthRatio",
                'Mapper_Adjust_Mapper_TargetWavelength' AS "Mapper_TargetWavelength",
                'Mapper_Adjust_Mapper_Wavelength(1.3um)' AS "Mapper_Wavelength(1.3um)",
                'Mapper_Adjust_Mapper_CheckingAdjustValue' AS "Mapper_CheckingAdjustValue",
                'Center_X' AS "Center_X",
                'Center_Y' AS "Center_Y",
                'Center_Lambda' AS "Center_Lambda",
                'Center_Intensity' AS "Center_Intensity",
                'Center_FWHM' AS "Center_FWHM",
                'Center_Tails' AS "Center_Tails",
                'Center_DeltaLambda' AS "Center_DeltaLambda",
                'A_X' AS "A_X",
                'A_Y' AS "A_Y",
                'A_Lambda' AS "A_Lambda",
                'A_Intensity' AS "A_Intensity",
                'A_FWHM' AS "A_FWHM",
                'A_Tails' AS "A_Tails",
                'A_DeltaLambda' AS "A_DeltaLambda",
                'B_X' AS "B_X",
                'B_Y' AS "B_Y",
                'B_Lambda' AS "B_Lambda",
                'B_Intensity' AS "B_Intensity",
                'B_FWHM' AS "B_FWHM",
                'B_Tails' AS "B_Tails",
                'B_DeltaLambda' AS "B_DeltaLambda",
                'C_X' AS "C_X",
                'C_Y' AS "C_Y",
                'C_Lambda' AS "C_Lambda",
                'C_Intensity' AS "C_Intensity",
                'C_FWHM' AS "C_FWHM",
                'C_Tails' AS "C_Tails",
                'C_DeltaLambda' AS "C_DeltaLambda",
                'D_X' AS "D_X",
                'D_Y' AS "D_Y",
                'D_Lambda' AS "D_Lambda",
                'D_Intensity' AS "D_Intensity",
                'D_FWHM' AS "D_FWHM",
                'D_Tails' AS "D_Tails",
                'D_DeltaLambda' AS "D_DeltaLambda",
                'AB_X' AS "AB_X",
                'AB_Y' AS "AB_Y",
                'AB_Lambda' AS "AB_Lambda",
                'AB_Intensity' AS "AB_Intensity",
                'AB_FWHM' AS "AB_FWHM",
                'AB_Tails' AS "AB_Tails",
                'AB_DeltaLambda' AS "AB_DeltaLambda",
                'AC_X' AS "AC_X",
                'AC_Y' AS "AC_Y",
                'AC_Lambda' AS "AC_Lambda",
                'AC_Intensity' AS "AC_Intensity",
                'AC_FWHM' AS "AC_FWHM",
                'AC_Tails' AS "AC_Tails",
                'AC_DeltaLambda' AS "AC_DeltaLambda",
                'BC_X' AS "BC_X",
                'BC_Y' AS "BC_Y",
                'BC_Lambda' AS "BC_Lambda",
                'BC_Intensity' AS "BC_Intensity",
                'BC_FWHM' AS "BC_FWHM",
                'BC_Tails' AS "BC_Tails",
                'BC_DeltaLambda' AS "BC_DeltaLambda",
                'CD_X' AS "CD_X",
                'CD_Y' AS "CD_Y",
                'CD_Lambda' AS "CD_Lambda",
                'CD_Intensity' AS "CD_Intensity",
                'CD_FWHM' AS "CD_FWHM",
                'CD_Tails' AS "CD_Tails",
                'CD_DeltaLambda' AS "CD_DeltaLambda",
                'AA_X' AS "AA_X",
                'AA_Y' AS "AA_Y",
                'AA_Lambda' AS "AA_Lambda",
                'AA_Intensity' AS "AA_Intensity",
                'AA_FWHM' AS "AA_FWHM",
                'AA_Tails' AS "AA_Tails",
                'AA_DeltaLambda' AS "AA_DeltaLambda",
                'BB_X' AS "BB_X",
                'BB_Y' AS "BB_Y",
                'BB_Lambda' AS "BB_Lambda",
                'BB_Intensity' AS "BB_Intensity",
                'BB_FWHM' AS "BB_FWHM",
                'BB_Tails' AS "BB_Tails",
                'BB_DeltaLambda' AS "BB_DeltaLambda",
                'CC_X' AS "CC_X",
                'CC_Y' AS "CC_Y",
                'CC_Lambda' AS "CC_Lambda",
                'CC_Intensity' AS "CC_Intensity",
                'CC_FWHM' AS "CC_FWHM",
                'CC_Tails' AS "CC_Tails",
                'CC_DeltaLambda' AS "CC_DeltaLambda",
                'DD_X' AS "DD_X",
                'DD_Y' AS "DD_Y",
                'DD_Lambda' AS "DD_Lambda",
                'DD_Intensity' AS "DD_Intensity",
                'DD_FWHM' AS "DD_FWHM",
                'DD_Tails' AS "DD_Tails",
                'DD_DeltaLambda' AS "DD_DeltaLambda",
                'Measurements_Addr32GravityLambda' AS "Addr32GravityLambda",
                'Measurements_AreaStandards_1' AS "AreaStandards_1",
                'Measurements_AreaStandards_2' AS "AreaStandards_2",
                'Mapper_PL' as "Mapper_PL"
            )
    )Format2
    ON Format1_Int_Data.SERIALNUMBER = Format2.SERIALNUMBER
WHERE 1=1
  AND Format1_Int_Data.SERIALNUMBER NOT IN 'DE065'

ORDER BY
    Format1_Int_Data."SORTED_DATA_STARTTIME_SORTED",
    Format1_STARTTIME
