SELECT 
H.SERIALNUMBER,
H.TESTHEADERID,
H.STARTTIME,
OPERATION,
V.OPERATOR,
V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME AS "KEY", V.VALUE
FROM TESTHEADER_V H
INNER JOIN MEASUREMENT_V V ON H.TESTHEADERID = V.TESTHEADERID
WHERE OPERATION in ( 'GRATING_CVD_Duty' ,'GRATING_Crystal_Duty')
ORDER BY H.STARTTIME, H.TESTHEADERID, V.MEASUREMENTPARAMETERID ASC;

SELECT 
    H.SERIALNUMBER,
    H.TESTHEADERID,
    H.STARTTIME,
    H.OPERATION,
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length1.Pitch' THEN V.VALUE END) AS "Length1.Pitch",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length2.Pitch' THEN V.VALUE END) AS "Length2.Pitch",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length3.Pitch' THEN V.VALUE END) AS "Length3.Pitch",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length4.Pitch' THEN V.VALUE END) AS "Length4.Pitch",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length5.Pitch' THEN V.VALUE END) AS "Length5.Pitch",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length1.Duty' THEN V.VALUE END) AS "Length1.Duty",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length2.Duty' THEN V.VALUE END) AS "Length2.Duty",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length3.Duty' THEN V.VALUE END) AS "Length3.Duty",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length4.Duty' THEN V.VALUE END) AS "Length4.Duty",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Length5.Duty' THEN V.VALUE END) AS "Length5.Duty",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Average.Duty' THEN V.VALUE END) AS "Average.Duty",
    MAX(CASE WHEN V.OPERATIONSTEPNAME || '.' || V.PARAMETERNAME = 'Average.3sigma' THEN V.VALUE END) AS "Average.3sigma"
FROM 
    TESTHEADER_V H
INNER JOIN 
    MEASUREMENT_V V 
ON 
    H.TESTHEADERID = V.TESTHEADERID
WHERE 
    H.OPERATION IN ('GRATING_CVD_Duty', 'GRATING_Crystal_Duty')
GROUP BY 
    H.SERIALNUMBER,
    H.TESTHEADERID,
    H.STARTTIME,
    H.OPERATION
ORDER BY 
    H.STARTTIME, 
    H.TESTHEADERID;
