SELECT
    Format1_Int_Data.STARTTIME AS Format1_STARTTIME,
    Format1_Int_Data.BATCHNUMBER,
    Format1_Int_Data.OPERATORID AS Format1_Operator,
    Format1_Int_Data.SERIALNUMBER,
    Format1_String_Data."NINE_SERIALNUMBER",
    Format1_Int_Data.PARTNUMBER,
    Format1_Int_Data."SORTED_DATA_STARTTIME_SORTED",
    Format1_Int_Data."SORTED_DATA_SORTNUMBER",
    Format1_MISC_Data."RecipeName_Macro",
    Format1_MISC_Data."RecipeName_Program",
    Format1_MISC_Data."RecipeName_Folder",
    Format1_Int_Data."SEM",
    Format1_Int_Data."PLmapper" AS Format1_PLmapper,
    Format1_Int_Data."XRD",
    Format1_Int_Data."MOCVD",
    Format1_Int_Data."X",
    Format1_Int_Data."Y",
    Format1_Int_Data."TargetWavelength",
    Format1_Int_Data."Thickness_Cap",
    Format1_Int_Data."Thickness_p-Q_115",
    Format1_Int_Data."Thickness_InP_Spacer1",
    Format1_Int_Data."Thickness_Core",
    Format1_Int_Data."Xray_Thickness",
    Format1_Int_Data."Xray_Strain",
    Format1_Int_Data."PL_Wavelength",
    Format1_Int_Data."PL_Intensity",
    Format1_Int_Data."PL_FWHM",
    Format1_Int_Data."PL_Adjust",
    Format1_Int_Data."Templature",
    Format1_Int_Data."Humidity",
    Format1_String_Data."LaserSideFilter1",
    Format1_Int_Data."LaserSideFilter2",
    Format1_Int_Data."Zvalue",
    Format1_Int_Data."PL_IntensityRate_A",
    Format1_Int_Data."PL_IntensityRate_B",
    Format1_Int_Data."PL_IntensityRate_C",
    Format1_Int_Data."PL_IntensityRate_D",
    Format1_Int_Data."Dulation_Step9",
    Format1_Int_Data."Dulation_Step13",
    Format1_Int_Data."Dulation_Step17",
    Format1_Int_Data."Dulation_Step21",
    Format1_Int_Data."Dulation_Step25",
    Format1_Int_Data."Dulation_Step26",
    Format1_Int_Data."Dulation_Step30",
    Format1_Int_Data."Dulation_Step34",
    Format1_Int_Data."Dulation_Step38",
    Format1_Int_Data."Dulation_Step42",
    Format1_Int_Data."Dulation_Step46",
    Format1_Int_Data."MO1-TMI_Step9",
    Format1_Int_Data."MO1-TMI_Step13",
    Format1_Int_Data."MO1-TMI_Step21",
    Format1_Int_Data."MO1-TMI_Step25",
    Format1_Int_Data."MO1-TMI_Step26",
    Format1_Int_Data."MO1-TMI_Step34",
    Format1_Int_Data."MO2-TEG_Step9",
    Format1_Int_Data."MO2-TEG_Step13",
    Format1_Int_Data."MO2-TEG_Step21",
    Format1_Int_Data."MO2-TEG_Step25",
    Format1_Int_Data."MO2-TEG_Step26",
    Format1_Int_Data."MO2-TEG_Step34",
    Format1_Int_Data."MO3-TMI_Step17",
    Format1_Int_Data."MO3-TMI_Step42",
    Format1_Int_Data."MO4-TEG_Step17",
    Format1_Int_Data."MO4-TEG_Step42",
    Format1_Int_Data."MO5-TMI_Step30",
    Format1_Int_Data."MO5-TMI_Step38",
    Format1_Int_Data."MO5-TMI_Step46",
    Format1_Int_Data."AsH3-A-20percent_Step42",
    Format1_Int_Data."AsH3-5percent_Step9",
    Format1_Int_Data."AsH3-5percent_Step13",
    Format1_Int_Data."AsH3-5percent_Step17",
    Format1_Int_Data."AsH3-5percent_Step21",
    Format1_Int_Data."AsH3-5percent_Step25",
    Format1_Int_Data."AsH3-5percent_Step26",
    Format1_Int_Data."AsH3-5percent_Step34",
    Format1_Int_Data."PH3-A-50percent_Step9",
    Format1_Int_Data."PH3-A-50percent_Step13",
    Format1_Int_Data."PH3-A-50percent_Step17",
    Format1_Int_Data."PH3-A-50percent_Step21",
    Format1_Int_Data."PH3-A-50percent_Step25",
    Format1_Int_Data."PH3-A-50percent_Step26",
    Format1_Int_Data."PH3-A-50percent_Step30",
    Format1_Int_Data."PH3-A-50percent_Step34",
    Format1_Int_Data."PH3-A-50percent_Step38",
    Format1_Int_Data."PH3-A-50percent_Step46",
    Format1_Int_Data."Si2H6-10ppm_Step9",
    Format1_Int_Data."DMZn-A-01percent_Step30",
    Format1_Int_Data."DMZn-A-01percent_Step34",
    Format1_Int_Data."DMZn-A-01percent_Step38",
    Format1_Int_Data."DMZn-A-01percent_Step42",
    Format1_Int_Data."DMZn-A-01percent_Step46",
    Format1_Int_Data."DMZn-B-01percent_Step26",
    Format1_Int_Data."GrowthTemperature_Step9",
    Format1_Int_Data."GrowthTemperature_Step13",
    Format1_Int_Data."GrowthTemperature_Step17",
    Format1_Int_Data."GrowthTemperature_Step21",
    Format1_Int_Data."GrowthTemperature_Step25",
    Format1_Int_Data."GrowthTemperature_Step26",
    Format1_Int_Data."GrowthTemperature_Step30",
    Format1_Int_Data."GrowthTemperature_Step34",
    Format1_Int_Data."GrowthTemperature_Step38",
    Format1_Int_Data."GrowthTemperature_Step42",
    Format1_Int_Data."GrowthTemperature_Step46",
    Format1_String_Data."LayerNo_Step9",
    Format1_String_Data."LayerNo_Step13",
    Format1_String_Data."LayerNo_Step17",
    Format1_String_Data."LayerNo_Step21",
    Format1_String_Data."LayerNo_Step25",
    Format1_String_Data."LayerNo_Step26",
    Format1_String_Data."LayerNo_Step30",
    Format1_String_Data."LayerNo_Step34",
    Format1_String_Data."LayerNo_Step38",
    Format1_String_Data."LayerNo_Step42",
    Format1_String_Data."LayerNo_Step46",
    Format1_String_Data."Comment_Step9",
    Format1_String_Data."Comment_Step13",
    Format1_String_Data."Comment_Step17",
    Format1_String_Data."Comment_Step21",
    Format1_String_Data."Comment_Step25",
    Format1_String_Data."Comment_Step26",
    Format1_String_Data."Comment_Step30",
    Format1_String_Data."Comment_Step34",
    Format1_String_Data."Comment_Step38",
    Format1_String_Data."Comment_Step42",
    Format1_String_Data."Comment_Step46",
    Format1_Int_Data."Thickness_Step_Step9",
    Format1_Int_Data."Thickness_Step_Step13",
    Format1_Int_Data."Thickness_Step_Step17",
    Format1_Int_Data."Thickness_Step_Step21",
    Format1_Int_Data."Thickness_Step_Step25",
    Format1_Int_Data."Thickness_Step_Step26",
    Format1_Int_Data."Thickness_Step_Step30",
    Format1_Int_Data."Thickness_Step_Step34",
    Format1_Int_Data."Thickness_Step_Step38",
    Format1_Int_Data."Thickness_Step_Step42",
    Format1_Int_Data."Thickness_Step_Step46",
    Format1_Int_Data."CarrierConcentration_Step9",
    Format1_Int_Data."CarrierConcentration_Step26",
    Format1_Int_Data."CarrierConcentration_Step30",
    Format1_Int_Data."CarrierConcentration_Step34",
    Format1_Int_Data."CarrierConcentration_Step38",
    Format1_Int_Data."CarrierConcentration_Step42",
    Format1_Int_Data."CarrierConcentration_Step46",
    Format1_Int_Data."Piezocon_F1",
    Format1_Int_Data."Piezocon_F1_Inverse",
    Format1_Int_Data."AsH3_5percent_BonbeDMZn",
    Format1_Int_Data."LD_CheckPLIntensity",
    Format1_Int_Data."BallastN2",
    Format1_Int_Data."DMZn_ConcAfterReplacing",
    Format1_Int_Data."DMZn_Conc",
    Format1_Int_Data."Volatility_5percentOrMore",
    Format1_Int_Data."MO-Temperature_MO1-TMI",
    Format1_Int_Data."MO-Temperature_MO2-TEG",
    Format1_Int_Data."MO-Temperature_MO3-TMI",
    Format1_Int_Data."MO-Temperature_MO4-TEG",
    Format1_Int_Data."MO-Temperature_MO5-TMI",
    Format1_Int_Data."MO-Temperature_MO6-TEG",
    Format1_Int_Data."MO-Temperature_Unused",
    Format2.STARTTIME AS Format2_STARTTIME,
    Format2.OPERATORID AS Format2_OPERATOR,
    Format2.SERIALNUMBER AS Format2_SERIALNUMBER,
    Format2."PLmapper" AS Format2_PLmapper,
    Format2."Mapper_Average_Mapper_PL_Lambda",
    Format2."Mapper_Average_Mapper_PL_Intensity",
    Format2."Mapper_Average_Mapper_PL_FWHM",
    Format2."Mapper_TargetWavelength",
    Format2."Mapper_Wavelength(1.3um)",
    Format2."Mapper_CheckingAdjustValue",
    Format2."Center_X",
    Format2."Center_Y",
    Format2."Center_Lambda",
    Format2."Center_Intensity",
    Format2."Center_FWHM",
    Format2."Center_Tails",
    Format2."Center_DeltaLambda",
    Format2."A_X",
    Format2."A_Y",
    Format2."A_Lambda",
    Format2."A_Intensity",
    Format2."A_FWHM",
    Format2."A_Tails",
    Format2."A_DeltaLambda",
    Format2."B_X",
    Format2."B_Y",
    Format2."B_Lambda",
    Format2."B_Intensity",
    Format2."B_FWHM",
    Format2."B_Tails",
    Format2."B_DeltaLambda",
    Format2."C_X",
    Format2."C_Y",
    Format2."C_Lambda",
    Format2."C_Intensity",
    Format2."C_FWHM",
    Format2."C_Tails",
    Format2."C_DeltaLambda",
    Format2."D_X",
    Format2."D_Y",
    Format2."D_Lambda",
    Format2."D_Intensity",
    Format2."D_FWHM",
    Format2."D_Tails",
    Format2."D_DeltaLambda",
    Format2."AB_X",
    Format2."AB_Y",
    Format2."AB_Lambda",
    Format2."AB_Intensity",
    Format2."AB_FWHM",
    Format2."AB_Tails",
    Format2."AB_DeltaLambda",
    Format2."AC_X",
    Format2."AC_Y",
    Format2."AC_Lambda",
    Format2."AC_Intensity",
    Format2."AC_FWHM",
    Format2."AC_Tails",
    Format2."AC_DeltaLambda",
    Format2."BC_X",
    Format2."BC_Y",
    Format2."BC_Lambda",
    Format2."BC_Intensity",
    Format2."BC_FWHM",
    Format2."BC_Tails",
    Format2."BC_DeltaLambda",
    Format2."CD_X",
    Format2."CD_Y",
    Format2."CD_Lambda",
    Format2."CD_Intensity",
    Format2."CD_FWHM",
    Format2."CD_Tails",
    Format2."CD_DeltaLambda",
    Format2."AA_X",
    Format2."AA_Y",
    Format2."AA_Lambda",
    Format2."AA_Intensity",
    Format2."AA_FWHM",
    Format2."AA_Tails",
    Format2."AA_DeltaLambda",
    Format2."BB_X",
    Format2."BB_Y",
    Format2."BB_Lambda",
    Format2."BB_Intensity",
    Format2."BB_FWHM",
    Format2."BB_Tails",
    Format2."BB_DeltaLambda",
    Format2."CC_X",
    Format2."CC_Y",
    Format2."CC_Lambda",
    Format2."CC_Intensity",
    Format2."CC_FWHM",
    Format2."CC_Tails",
    Format2."CC_DeltaLambda",
    Format2."DD_X",
    Format2."DD_Y",
    Format2."DD_Lambda",
    Format2."DD_Intensity",
    Format2."DD_FWHM",
    Format2."DD_Tails",
    Format2."DD_DeltaLambda"
FROM(
    SELECT
        HDR.TESTHEADERID,
        HDR.STARTTIME,
        HDR.PARTNUMBER,
        HDR.SERIALNUMBER,
        HDR.OPERATORID,
        HDR.BATCHNUMBER,
        MAX(CASE TEQ.DEVICENAME WHEN 'SEM' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "SEM",
        MAX(CASE TEQ.DEVICENAME WHEN 'PLmapper' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "PLmapper",
        MAX(CASE TEQ.DEVICENAME WHEN 'XRD' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "XRD",
        MAX(CASE TEQ.DEVICENAME WHEN 'MOCVD' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "MOCVD",
        OPS.OPERATIONSTEPNAME || '_' || PARAMETERNAME AS TESTSTEPS,
        MSD.VALUE
    FROM
        TDSMFG.TESTHEADER           HDR,
        TDSMFG.TESTHEADERMISC       THM,
        TDSMFG.TESTHEADERSTEP       HDS,
        TDSMFG.OPERATIONSTEP        OPS,
        TDSMFG.MEASUREMENTPARAMETER MSP,
        TDSMFG.MEASUREMENT          MSD,
        TDSMFG.PARAMETER            PAR,
        TDSMFG.TESTEQUIPMENT        TEQ
    WHERE 1=1
        AND HDR.TESTHEADERID            = HDS.TESTHEADERID
        AND HDR.TESTHEADERID            = THM.TESTHEADERID
        AND HDS.OPERATIONSTEPID         = OPS.OPERATIONSTEPID
        AND HDS.TESTHEADERSTEPID        = MSP.TESTHEADERSTEPID
        AND MSP.MEASUREMENTPARAMETERID  = MSD.MEASUREMENTPARAMETERID
        AND MSP.PARAMETERID             = PAR.PARAMETERID
        AND TEQ.TESTHEADERID(+)         = HDR.TESTHEADERID
        AND HDR.OPERATION               = 'LD-EML_F1_Format1'
    GROUP BY
        HDR.TESTHEADERID,
        STARTTIME,
        PARTNUMBER,
        SERIALNUMBER,
        OPERATORID,
        BATCHNUMBER,
        OPERATIONSTEPNAME,
        PARAMETERNAME,
        VALUE
    )
    PIVOT(
        MAX(VALUE) FOR TESTSTEPS IN(
            'Coordinate_X' AS "X",
            'Coordinate_Y' AS "Y",
            'TargetWavelength_TargetWavelength' AS "TargetWavelength",
            'Thickness_Thickness_Cap' AS "Thickness_Cap",
            'Thickness_Thickness_p-Q_115' AS "Thickness_p-Q_115",
            'Thickness_Thickness_InP_Spacer1' AS "Thickness_InP_Spacer1",
            'Thickness_Thickness_Core' AS "Thickness_Core",
            'XRayDiffraction_Xray_Thickness' AS "Xray_Thickness",
            'XRayDiffraction_Xray_Strain' AS "Xray_Strain",
            'Adjust_PL_Wavelength' AS "PL_Wavelength",
            'Adjust_PL_Intensity' AS "PL_Intensity",
            'Adjust_PL_FWHM' AS "PL_FWHM",
            'Adjust_PL_Adjust' AS "PL_Adjust",
            'MeasurementConditions_Templature' AS "Templature",
            'MeasurementConditions_Humidity' AS "Humidity",
            'MeasurementConditions_LaserSideFilter2' AS "LaserSideFilter2",
            'MeasurementConditions_Zvalue' AS "Zvalue",
            'MeasurementConditions_PL_IntensityRate_A' AS "PL_IntensityRate_A",
            'MeasurementConditions_PL_IntensityRate_B' AS "PL_IntensityRate_B",
            'MeasurementConditions_PL_IntensityRate_C' AS "PL_IntensityRate_C",
            'MeasurementConditions_PL_IntensityRate_D' AS "PL_IntensityRate_D",
            'Dulation_Step9' AS "Dulation_Step9",
            'Dulation_Step13' AS "Dulation_Step13",
            'Dulation_Step17' AS "Dulation_Step17",
            'Dulation_Step21' AS "Dulation_Step21",
            'Dulation_Step25' AS "Dulation_Step25",
            'Dulation_Step26' AS "Dulation_Step26",
            'Dulation_Step30' AS "Dulation_Step30",
            'Dulation_Step34' AS "Dulation_Step34",
            'Dulation_Step38' AS "Dulation_Step38",
            'Dulation_Step42' AS "Dulation_Step42",
            'Dulation_Step46' AS "Dulation_Step46",
            'MO1-TMI_Step9' AS "MO1-TMI_Step9",
            'MO1-TMI_Step13' AS "MO1-TMI_Step13",
            'MO1-TMI_Step21' AS "MO1-TMI_Step21",
            'MO1-TMI_Step25' AS "MO1-TMI_Step25",
            'MO1-TMI_Step26' AS "MO1-TMI_Step26",
            'MO1-TMI_Step34' AS "MO1-TMI_Step34",
            'MO2-TEG_Step9' AS "MO2-TEG_Step9",
            'MO2-TEG_Step13' AS "MO2-TEG_Step13",
            'MO2-TEG_Step21' AS "MO2-TEG_Step21",
            'MO2-TEG_Step25' AS "MO2-TEG_Step25",
            'MO2-TEG_Step26' AS "MO2-TEG_Step26",
            'MO2-TEG_Step34' AS "MO2-TEG_Step34",
            'MO3-TMI_Step17' AS "MO3-TMI_Step17",
            'MO3-TMI_Step42' AS "MO3-TMI_Step42",
            'MO4-TEG_Step17' AS "MO4-TEG_Step17",
            'MO4-TEG_Step42' AS "MO4-TEG_Step42",
            'MO5-TMI_Step30' AS "MO5-TMI_Step30",
            'MO5-TMI_Step38' AS "MO5-TMI_Step38",
            'MO5-TMI_Step46' AS "MO5-TMI_Step46",
            'AsH3-A-20percent_Step42' AS "AsH3-A-20percent_Step42",
            'AsH3-5percent_Step9' AS "AsH3-5percent_Step9",
            'AsH3-5percent_Step13' AS "AsH3-5percent_Step13",
            'AsH3-5percent_Step17' AS "AsH3-5percent_Step17",
            'AsH3-5percent_Step21' AS "AsH3-5percent_Step21",
            'AsH3-5percent_Step25' AS "AsH3-5percent_Step25",
            'AsH3-5percent_Step26' AS "AsH3-5percent_Step26",
            'AsH3-5percent_Step34' AS "AsH3-5percent_Step34",
            'PH3-A-50percent_Step9' AS "PH3-A-50percent_Step9",
            'PH3-A-50percent_Step13' AS "PH3-A-50percent_Step13",
            'PH3-A-50percent_Step17' AS "PH3-A-50percent_Step17",
            'PH3-A-50percent_Step21' AS "PH3-A-50percent_Step21",
            'PH3-A-50percent_Step25' AS "PH3-A-50percent_Step25",
            'PH3-A-50percent_Step26' AS "PH3-A-50percent_Step26",
            'PH3-A-50percent_Step30' AS "PH3-A-50percent_Step30",
            'PH3-A-50percent_Step34' AS "PH3-A-50percent_Step34",
            'PH3-A-50percent_Step38' AS "PH3-A-50percent_Step38",
            'PH3-A-50percent_Step46' AS "PH3-A-50percent_Step46",
            'Si2H6-10ppm_Step9' AS "Si2H6-10ppm_Step9",
            'DMZn-A-01percent_Step30' AS "DMZn-A-01percent_Step30",
            'DMZn-A-01percent_Step34' AS "DMZn-A-01percent_Step34",
            'DMZn-A-01percent_Step38' AS "DMZn-A-01percent_Step38",
            'DMZn-A-01percent_Step42' AS "DMZn-A-01percent_Step42",
            'DMZn-A-01percent_Step46' AS "DMZn-A-01percent_Step46",
            'DMZn-B-01percent_Step26' AS "DMZn-B-01percent_Step26",
            'GrowthTemperature_Step9' AS "GrowthTemperature_Step9",
            'GrowthTemperature_Step13' AS "GrowthTemperature_Step13",
            'GrowthTemperature_Step17' AS "GrowthTemperature_Step17",
            'GrowthTemperature_Step21' AS "GrowthTemperature_Step21",
            'GrowthTemperature_Step25' AS "GrowthTemperature_Step25",
            'GrowthTemperature_Step26' AS "GrowthTemperature_Step26",
            'GrowthTemperature_Step30' AS "GrowthTemperature_Step30",
            'GrowthTemperature_Step34' AS "GrowthTemperature_Step34",
            'GrowthTemperature_Step38' AS "GrowthTemperature_Step38",
            'GrowthTemperature_Step42' AS "GrowthTemperature_Step42",
            'GrowthTemperature_Step46' AS "GrowthTemperature_Step46",
            'Thickness_Step_Step9' AS "Thickness_Step_Step9",
            'Thickness_Step_Step13' AS "Thickness_Step_Step13",
            'Thickness_Step_Step17' AS "Thickness_Step_Step17",
            'Thickness_Step_Step21' AS "Thickness_Step_Step21",
            'Thickness_Step_Step25' AS "Thickness_Step_Step25",
            'Thickness_Step_Step26' AS "Thickness_Step_Step26",
            'Thickness_Step_Step30' AS "Thickness_Step_Step30",
            'Thickness_Step_Step34' AS "Thickness_Step_Step34",
            'Thickness_Step_Step38' AS "Thickness_Step_Step38",
            'Thickness_Step_Step42' AS "Thickness_Step_Step42",
            'Thickness_Step_Step46' AS "Thickness_Step_Step46",
            'CarrierConcentration_Step9' AS "CarrierConcentration_Step9",
            'CarrierConcentration_Step26' AS "CarrierConcentration_Step26",
            'CarrierConcentration_Step30' AS "CarrierConcentration_Step30",
            'CarrierConcentration_Step34' AS "CarrierConcentration_Step34",
            'CarrierConcentration_Step38' AS "CarrierConcentration_Step38",
            'CarrierConcentration_Step42' AS "CarrierConcentration_Step42",
            'CarrierConcentration_Step46' AS "CarrierConcentration_Step46",
            'Piezocon_F1' AS "Piezocon_F1",
            'Piezocon_F1_Inverse' AS "Piezocon_F1_Inverse",
            'AsH3_BonbeConc_AsH3_5percent_BonbeDMZn' AS "AsH3_5percent_BonbeDMZn",
            'LD_CheckPLIntensity_LD_CheckPLIntensity' AS "LD_CheckPLIntensity",
            'BallastN2_BallastN2' AS "BallastN2",
            'DMZn_Conc_DMZn_ConcAfterReplacing' AS "DMZn_ConcAfterReplacing",
            'DMZn_Conc_DMZn_Conc' AS "DMZn_Conc",
            'DMZn_Conc_Volatility_5percentOrMore' AS "Volatility_5percentOrMore",
            'MO-Temperature_MO1-TMI' AS "MO-Temperature_MO1-TMI",
            'MO-Temperature_MO2-TEG' AS "MO-Temperature_MO2-TEG",
            'MO-Temperature_MO3-TMI' AS "MO-Temperature_MO3-TMI",
            'MO-Temperature_MO4-TEG' AS "MO-Temperature_MO4-TEG",
            'MO-Temperature_MO5-TMI' AS "MO-Temperature_MO5-TMI",
            'MO-Temperature_MO6-TEG' AS "MO-Temperature_MO6-TEG",
            'MO-Temperature_Unused' AS "MO-Temperature_Unused",
            'SORTED_DATA_STARTTIME_SORTED' AS "SORTED_DATA_STARTTIME_SORTED",
            'SORTED_DATA_SORTNUMBER' AS "SORTED_DATA_SORTNUMBER"
        )
    )Format1_Int_Data
    LEFT JOIN
    (
        SELECT
            HDR.SERIALNUMBER,
            THM.MISCVALUE,
            THM.MISCDESC
        FROM
            TDSMFG.TESTHEADER           HDR,
            TDSMFG.TESTHEADERMISC       THM
        WHERE
            HDR.TESTHEADERID            = THM.TESTHEADERID
            AND HDR.OPERATION           = 'LD-EML_F1_Format1'
    )
    PIVOT(
        MAX(MISCVALUE) FOR MISCDESC IN(
            'RecipeName-Macro' AS "RecipeName_Macro",
            'RecipeName-Program' AS "RecipeName_Program",
            'RecipeName-Folder' AS "RecipeName_Folder"
        )
    )Format1_MISC_Data
    ON Format1_Int_Data.SERIALNUMBER = Format1_MISC_Data.SERIALNUMBER
    LEFT JOIN
    (
        SELECT
            HDR.TESTHEADERID,
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'MeasurementConditions_LaserSideFilter1' THEN VALUESTRING END) AS "LaserSideFilter1",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'SORTED_DATA_LotNumber_5' THEN VALUESTRING END) AS "FIVE_SERIALNUMBER",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'SORTED_DATA_LotNumber_9' THEN VALUESTRING END) AS "NINE_SERIALNUMBER",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step9' THEN VALUESTRING END) AS "LayerNo_Step9",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step13' THEN VALUESTRING END) AS "LayerNo_Step13",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step17' THEN VALUESTRING END) AS "LayerNo_Step17",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step21' THEN VALUESTRING END) AS "LayerNo_Step21",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step25' THEN VALUESTRING END) AS "LayerNo_Step25",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step26' THEN VALUESTRING END) AS "LayerNo_Step26",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step30' THEN VALUESTRING END) AS "LayerNo_Step30",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step34' THEN VALUESTRING END) AS "LayerNo_Step34",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step38' THEN VALUESTRING END) AS "LayerNo_Step38",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step42' THEN VALUESTRING END) AS "LayerNo_Step42",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'LayerNo_Step46' THEN VALUESTRING END) AS "LayerNo_Step46",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step9' THEN VALUESTRING END) AS "Comment_Step9",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step13' THEN VALUESTRING END) AS "Comment_Step13",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step17' THEN VALUESTRING END) AS "Comment_Step17",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step21' THEN VALUESTRING END) AS "Comment_Step21",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step25' THEN VALUESTRING END) AS "Comment_Step25",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step26' THEN VALUESTRING END) AS "Comment_Step26",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step30' THEN VALUESTRING END) AS "Comment_Step30",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step34' THEN VALUESTRING END) AS "Comment_Step34",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step38' THEN VALUESTRING END) AS "Comment_Step38",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step42' THEN VALUESTRING END) AS "Comment_Step42",
            MAX(CASE OPERATIONSTEPNAME || '_' || PARAMETERNAME WHEN 'Comment_Step46' THEN VALUESTRING END) AS "Comment_Step46"
        FROM
            TDSMFG.TESTHEADER           HDR,
            TDSMFG.TESTHEADERSTEP       HDS,
            TDSMFG.OPERATIONSTEP        OPS,
            TDSMFG.PARAMETER            PAR,
            TDSMFG.STRINGPARAMETER      STP,
            TDSMFG.STRINGMEASUREMENT    SMM
        WHERE 1=1
            AND HDR.TESTHEADERID            = HDS.TESTHEADERID
            AND HDS.OPERATIONSTEPID         = OPS.OPERATIONSTEPID
            AND HDS.TESTHEADERSTEPID        = STP.TESTHEADERSTEPID
            AND STP.STRINGPARAMETERID       = SMM.STRINGPARAMETERID
            AND PAR.OPERATIONSTEPID         = OPS.OPERATIONSTEPID
            AND PAR.PARAMETERID             = STP.PARAMETERID
            AND HDR.OPERATION               = 'LD-EML_F1_Format1'
        GROUP BY
            HDR.TESTHEADERID
    )Format1_String_Data
    ON Format1_Int_Data.TESTHEADERID = Format1_String_Data.TESTHEADERID
    FULL JOIN
    (
        SELECT
            HDR.TESTHEADERID,
            HDR.STARTTIME,
            HDR.PARTNUMBER,
            HDR.SERIALNUMBER,
            HDR.OPERATORID,
            HDR.BATCHNUMBER,
            MAX(CASE TEQ.DEVICENAME WHEN 'PLmapper' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "PLmapper",
            MAX(CASE TEQ.DEVICENAME WHEN 'MOCVD' THEN TEQ.DEVICENAME || TEQ.DEVICESERIALNUMBER END) AS "MOCVD",
            OPS.OPERATIONSTEPNAME || '_' || PARAMETERNAME AS TESTSTEPS,
            MSD.VALUE
        FROM
            TDSMFG.TESTHEADER           HDR,
            TDSMFG.TESTHEADERSTEP       HDS,
            TDSMFG.OPERATIONSTEP        OPS,
            TDSMFG.MEASUREMENTPARAMETER MSP,
            TDSMFG.MEASUREMENT          MSD,
            TDSMFG.PARAMETER            PAR,
            TDSMFG.TESTEQUIPMENT        TEQ
        WHERE 1=1
            AND HDR.TESTHEADERID            = HDS.TESTHEADERID
            AND HDS.OPERATIONSTEPID         = OPS.OPERATIONSTEPID
            AND HDS.TESTHEADERSTEPID        = MSP.TESTHEADERSTEPID
            AND MSP.MEASUREMENTPARAMETERID  = MSD.MEASUREMENTPARAMETERID
            AND MSP.PARAMETERID             = PAR.PARAMETERID
            AND TEQ.TESTHEADERID(+)         = HDR.TESTHEADERID
            AND HDR.OPERATION               = 'LD-EML_F1_Format2'
        GROUP BY
            HDR.TESTHEADERID,
            STARTTIME,
            PARTNUMBER,
            SERIALNUMBER,
            OPERATORID,
            BATCHNUMBER,
            OPERATIONSTEPNAME,
            PARAMETERNAME,
            VALUE
        )
        PIVOT(
            MAX(VALUE) FOR TESTSTEPS IN(
                'Coordinate_X' AS "X",
                'Coordinate_Y' AS "Y",
                'Mapper_Average_Mapper_PL_Lambda' AS "Mapper_Average_Mapper_PL_Lambda",
                'Mapper_Average_Mapper_PL_Intensity' AS "Mapper_Average_Mapper_PL_Intensity",
                'Mapper_Average_Mapper_PL_FWHM' AS "Mapper_Average_Mapper_PL_FWHM",
                'Mapper_Adjust_Mapper_TargetWavelength' AS "Mapper_TargetWavelength",
                'Mapper_Adjust_Mapper_Wavelength(1.3um)' AS "Mapper_Wavelength(1.3um)",
                'Mapper_Adjust_Mapper_CheckingAdjustValue' AS "Mapper_CheckingAdjustValue",
                'Center_X' AS "Center_X",
                'Center_Y' AS "Center_Y",
                'Center_Lambda' AS "Center_Lambda",
                'Center_Intensity' AS "Center_Intensity",
                'Center_FWHM' AS "Center_FWHM",
                'Center_Tails' AS "Center_Tails",
                'Center_DeltaLambda' AS "Center_DeltaLambda",
                'A_X' AS "A_X",
                'A_Y' AS "A_Y",
                'A_Lambda' AS "A_Lambda",
                'A_Intensity' AS "A_Intensity",
                'A_FWHM' AS "A_FWHM",
                'A_Tails' AS "A_Tails",
                'A_DeltaLambda' AS "A_DeltaLambda",
                'B_X' AS "B_X",
                'B_Y' AS "B_Y",
                'B_Lambda' AS "B_Lambda",
                'B_Intensity' AS "B_Intensity",
                'B_FWHM' AS "B_FWHM",
                'B_Tails' AS "B_Tails",
                'B_DeltaLambda' AS "B_DeltaLambda",
                'C_X' AS "C_X",
                'C_Y' AS "C_Y",
                'C_Lambda' AS "C_Lambda",
                'C_Intensity' AS "C_Intensity",
                'C_FWHM' AS "C_FWHM",
                'C_Tails' AS "C_Tails",
                'C_DeltaLambda' AS "C_DeltaLambda",
                'D_X' AS "D_X",
                'D_Y' AS "D_Y",
                'D_Lambda' AS "D_Lambda",
                'D_Intensity' AS "D_Intensity",
                'D_FWHM' AS "D_FWHM",
                'D_Tails' AS "D_Tails",
                'D_DeltaLambda' AS "D_DeltaLambda",
                'AB_X' AS "AB_X",
                'AB_Y' AS "AB_Y",
                'AB_Lambda' AS "AB_Lambda",
                'AB_Intensity' AS "AB_Intensity",
                'AB_FWHM' AS "AB_FWHM",
                'AB_Tails' AS "AB_Tails",
                'AB_DeltaLambda' AS "AB_DeltaLambda",
                'AC_X' AS "AC_X",
                'AC_Y' AS "AC_Y",
                'AC_Lambda' AS "AC_Lambda",
                'AC_Intensity' AS "AC_Intensity",
                'AC_FWHM' AS "AC_FWHM",
                'AC_Tails' AS "AC_Tails",
                'AC_DeltaLambda' AS "AC_DeltaLambda",
                'BC_X' AS "BC_X",
                'BC_Y' AS "BC_Y",
                'BC_Lambda' AS "BC_Lambda",
                'BC_Intensity' AS "BC_Intensity",
                'BC_FWHM' AS "BC_FWHM",
                'BC_Tails' AS "BC_Tails",
                'BC_DeltaLambda' AS "BC_DeltaLambda",
                'CD_X' AS "CD_X",
                'CD_Y' AS "CD_Y",
                'CD_Lambda' AS "CD_Lambda",
                'CD_Intensity' AS "CD_Intensity",
                'CD_FWHM' AS "CD_FWHM",
                'CD_Tails' AS "CD_Tails",
                'CD_DeltaLambda' AS "CD_DeltaLambda",
                'AA_X' AS "AA_X",
                'AA_Y' AS "AA_Y",
                'AA_Lambda' AS "AA_Lambda",
                'AA_Intensity' AS "AA_Intensity",
                'AA_FWHM' AS "AA_FWHM",
                'AA_Tails' AS "AA_Tails",
                'AA_DeltaLambda' AS "AA_DeltaLambda",
                'BB_X' AS "BB_X",
                'BB_Y' AS "BB_Y",
                'BB_Lambda' AS "BB_Lambda",
                'BB_Intensity' AS "BB_Intensity",
                'BB_FWHM' AS "BB_FWHM",
                'BB_Tails' AS "BB_Tails",
                'BB_DeltaLambda' AS "BB_DeltaLambda",
                'CC_X' AS "CC_X",
                'CC_Y' AS "CC_Y",
                'CC_Lambda' AS "CC_Lambda",
                'CC_Intensity' AS "CC_Intensity",
                'CC_FWHM' AS "CC_FWHM",
                'CC_Tails' AS "CC_Tails",
                'CC_DeltaLambda' AS "CC_DeltaLambda",
                'DD_X' AS "DD_X",
                'DD_Y' AS "DD_Y",
                'DD_Lambda' AS "DD_Lambda",
                'DD_Intensity' AS "DD_Intensity",
                'DD_FWHM' AS "DD_FWHM",
                'DD_Tails' AS "DD_Tails",
                'DD_DeltaLambda' AS "DD_DeltaLambda"
            )
    )Format2
    ON Format1_Int_Data.SERIALNUMBER = Format2.SERIALNUMBER

ORDER BY
    Format1_Int_Data."SORTED_DATA_STARTTIME_SORTED",
    Format1_STARTTIME
